baseURL = "/"
languageCode = "cn"
DefaultContentLanguage = "zh"
title = "猪八的网：浮生志"
copyright = "Zhu8, [<a href=\"https://creativecommons.org/licenses/by-sa/4.0/deed.zh\">CC BY-SA</a>]"
theme = "hugo-theme-tokiwa"
googleAnalytics = "G-5HJRD89DCW" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
canonifyurls = true
footnoteReturnLinkContents = "↩"
preserveTaxonomyNames = true
hasCJKLanguage = true
enableInlineShortcodes = true
author = "Zhu8"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
  math = false
  toc = true
  env = "production"
  description = """
  庸俗路上的无尽狂奔……
  """
  favicon = "/favicon.ico"
  fuse = true 
  useChineseFonts = true
  bannerFont = "fonts/杨任东竹石体-Light"
  PostDateFormat = "Mon, 02 Jan 2006 15:04:05 MST"
  enableReadingTime = true
  author = "Zhu8"
  authorlocation = "Nanjing, China"
  authorwebsite = "https://zhu8.net/"
  githubName = "Zhu8"
  email = "zhu8@msn.com"
  twitterName = "5CJ"
  sitedescription = "陈俊［ChenJun(Zhu8)］的个人网站，江苏金坛人士，现居金陵，83年生人，电子产品、代码、海淘 、智能设备、网页设计自虐狂，曼联死忠粉，王小波门下走狗。"
  enableWaline = true
  googleSiteVerification = "Mfl8lf6NN0DWPluv8lQpBL-mrKi22ZOcnlKXYURni1Y"
  appletouchicon ="/apple-touch-icon.png"
  walineServer = "https://comm.zhu8.net/"
	
[permalinks]
  posts = "/blog/:year/:month/:slug/"
  categories = "/categories/:slug/"
[taxonomies]
   tag = "tags"
   category = "categories"
   blog = "archives"
[menu]
# Shown in the side menu.
[[menu.main]]
	identifier = "blog"
	url = "/blog/"
	name = "Blog § 日志"
	weight = 1
	pre = "<i class=\"fas fa-book\"></i>"
[[menu.main]]
	identifier = "about"
	name = "About § 关于"
	weight = 2
	url = "/about/"
	pre = "<i class=\"fas fa-address-book\"></i>"
[[menu.main]]
	identifier = "links"
	url = "/links/"
	name = "Links § 链接"
	weight = 3
	pre = "<i class=\"fas fa-link\"></i>"
[[menu.main]]
	identifier = "project"
	url = "/project/"
	name = "Project § 项目"
	weight = 4
	pre = "<i class=\"fas fa-poo\"></i>"
[[menu.main]]
	identifier = "categories"
	url = "/categories/"
	name = "Categories § 分类"
	weight = 5
	pre = "<i class=\"fas fa-th-list\"></i>"
[[menu.main]]
	identifier = "tags"
	url = "/tags/"
	name = "Tags § 标签"
	weight = 6
	pre = "<i class=\"fas fa-tag\"></i>"
[[menu.main]]
	identifier = "rss"
	url = "/index.xml"
	name = "RSS § 订阅"
	weight = 7
	pre = "<i class=\"fas fa-rss\"></i>"
[social]
github = "https://github.com/zhu8"
gitlab = "https://gitlab.com/zhu8.net"
twitter = "https://twitter.com/5CJ"
weibo = "https://weibo.com/zhu8"
douban = "https://douban.com/people/zhu8"
tumblr = "https://zhu8.tumblr.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]